#include "utilities/utils.hpp"


auto main() -> int try {

}

catch (std::exception const& exception) {
    std::cerr << "Error: " << exception.what() << '\n';
}